import React, { useState, useRef, useEffect, useCallback } from 'react'

// ── Project metadata ─────────────────────────────────────────────────────────
// Each entry maps a video filename to a human-readable project title + category.
// Thumbnails are auto-generated by seeking to 1 s inside the video on the client.
const PROJECT_DATA: { file: string; title: string; category: string }[] = [
  { file: 'video_1.mp4',  title: 'DAMAC Luxury Tower',           category: 'Architectural Viz' },
  { file: 'video_2.mp4',  title: 'Ambient Desert Villa',          category: 'Architectural Viz' },
  { file: 'video_3.mp4',  title: 'World Government Summit',       category: 'Event Design'       },
  { file: 'video_4.mp4',  title: 'TAG Heuer Brand Activation',    category: 'Event Design'       },
  { file: 'video_5.mp4',  title: 'Real-Time Cityscape',           category: 'Real-Time UE5'     },
  { file: 'video_6.mp4',  title: 'Montblanc Showcase',            category: 'Event Design'       },
  { file: 'video_7.mp4',  title: 'Dubai Marina Penthouse',        category: 'Architectural Viz' },
  { file: 'video_8.mp4',  title: 'Samsung Galaxy Stage',          category: 'Event Design'       },
  { file: 'video_9.mp4',  title: 'Interior Light Study',          category: 'Look Dev'          },
  { file: 'video_10.mp4', title: 'Huawei Tech Conference',        category: 'Event Design'       },
  { file: 'video_11.mp4', title: 'Volumetric Fog Render',         category: 'Look Dev'          },
  { file: 'video_12.mp4', title: 'Omniyat Branded Residence',     category: 'Architectural Viz' },
  { file: 'video_13.mp4', title: 'Night Skyline Study',           category: 'Real-Time UE5'     },
  { file: 'video_14.mp4', title: 'Richard Mille Pop-Up',          category: 'Event Design'       },
  { file: 'video_15.mp4', title: 'Dubai Holding Masterplan',      category: 'Architectural Viz' },
  { file: 'video_16.mp4', title: 'Vodafone Arena Stage',          category: 'Event Design'       },
  { file: 'video_17.mp4', title: 'G20 Saudi Arabia Pavilion',     category: 'Event Design'       },
  { file: 'video_18.mp4', title: 'Warner Bros Cinematic Set',     category: 'Look Dev'          },
  { file: 'video_19.mp4', title: 'Ministry of Transport Hub',     category: 'Architectural Viz' },
  { file: 'video_20.mp4', title: 'Sandstorm Environment',         category: 'Real-Time UE5'     },
  { file: 'video_21.mp4', title: 'Entourage Mega-Event Stage',    category: 'Event Design'       },
  { file: 'video_22.mp4', title: 'Ambient Studio Landscape',      category: 'Architectural Viz' },
  { file: 'video_23.mp4', title: 'OD Events Keynote Stage',       category: 'Event Design'       },
  { file: 'video_24.mp4', title: 'Glass Villa Interior',          category: 'Architectural Viz' },
  { file: 'video_25.mp4', title: 'InDesign Showroom Cairo',       category: 'Architectural Viz' },
  { file: 'video_26.mp4', title: 'Cinematic Character Rig',       category: 'Look Dev'          },
  { file: 'video_27.mp4', title: 'Hyperrealistic Terrain',        category: 'Real-Time UE5'     },
  { file: 'video_28.mp4', title: 'Luxury Retail Entrance',        category: 'Architectural Viz' },
]

const ALL_CATEGORIES = ['All', 'Architectural Viz', 'Event Design', 'Real-Time UE5', 'Look Dev']

// Generates a poster frame from a video by seeking to 1 second
function usePoster(src: string) {
  const [poster, setPoster] = useState<string>('')

  useEffect(() => {
    const video = document.createElement('video')
    video.src = src
    video.crossOrigin = 'anonymous'
    video.muted = true
    video.preload = 'metadata'

    const capture = () => {
      const canvas = document.createElement('canvas')
      canvas.width = 640
      canvas.height = 360
      const ctx = canvas.getContext('2d')
      if (ctx) {
        ctx.drawImage(video, 0, 0, canvas.width, canvas.height)
        setPoster(canvas.toDataURL('image/jpeg', 0.85))
      }
    }

    const onLoaded = () => {
      // Seek to 1s for a visually rich thumbnail frame since intro is removed
      const seekTarget = Math.min(1, Math.max(0, video.duration - 0.1))
      video.currentTime = seekTarget
    }

    video.addEventListener('loadedmetadata', onLoaded, { once: true })
    video.addEventListener('seeked', capture, { once: true })
    // Fallback if loadedmetadata already fired
    video.addEventListener('loadeddata', () => {
      if (video.currentTime === 0) onLoaded()
    }, { once: true })

    return () => {
      video.src = ''
    }
  }, [src])

  return poster
}

// Individual gallery card
function VideoCard({
  project,
  onClick,
  index,
}: {
  project: typeof PROJECT_DATA[0]
  onClick: () => void
  index: number
}) {
  const src = `https://pub-340c09903d0b49fea4aec85224bcb1bb.r2.dev/${project.file}`
  const poster = usePoster(src)
  const videoRef = useRef<HTMLVideoElement>(null)
  const [hovered, setHovered] = useState(false)

  const handleMouseEnter = () => {
    setHovered(true)
    if (videoRef.current) {
      videoRef.current.currentTime = 0
      videoRef.current.play().catch(() => {})
    }
  }
  const handleMouseLeave = () => {
    setHovered(false)
    if (videoRef.current) {
      videoRef.current.pause()
      videoRef.current.currentTime = 0
    }
  }

  return (
    <div
      className="vg-card"
      style={{ animationDelay: `${index * 60}ms` }}
      onMouseEnter={handleMouseEnter}
      onMouseLeave={handleMouseLeave}
      onClick={onClick}
    >
      <div className="vg-card-media">
        {poster && <img className="vg-poster" src={poster} alt={project.title} />}
        <video
          ref={videoRef}
          className={`vg-video ${hovered ? 'vg-video--visible' : ''}`}
          src={src}
          muted
          loop
          playsInline
          preload="none"
        />
        <div className={`vg-overlay ${hovered ? 'vg-overlay--visible' : ''}`}>
          <div className="vg-play-ring">
            <svg viewBox="0 0 24 24" fill="currentColor" width="24" height="24">
              <polygon points="5,3 19,12 5,21" />
            </svg>
          </div>
        </div>
        <span className="vg-category-badge">{project.category}</span>
      </div>
      <div className="vg-card-info">
        <h3 className="vg-title">{project.title}</h3>
        <div className="vg-meta">
          <span className="vg-tag">{project.category}</span>
          <span className="vg-watch">Watch ›</span>
        </div>
      </div>
    </div>
  )
}

// Lightbox modal
function Lightbox({
  project,
  onClose,
  onPrev,
  onNext,
}: {
  project: typeof PROJECT_DATA[0]
  onClose: () => void
  onPrev: () => void
  onNext: () => void
}) {
  useEffect(() => {
    const handleKey = (e: KeyboardEvent) => {
      if (e.key === 'Escape') onClose()
      if (e.key === 'ArrowRight') onNext()
      if (e.key === 'ArrowLeft') onPrev()
    }
    document.addEventListener('keydown', handleKey)
    return () => document.removeEventListener('keydown', handleKey)
  }, [onClose, onNext, onPrev])

  useEffect(() => {
    document.body.style.overflow = 'hidden'
    return () => { document.body.style.overflow = '' }
  }, [])

  return (
    <div className="vg-lightbox" onClick={onClose}>
      <div className="vg-lightbox-inner" onClick={e => e.stopPropagation()}>
        <button className="vg-lb-close" onClick={onClose}>✕</button>
        <button className="vg-lb-nav vg-lb-prev" onClick={onPrev}>‹</button>
        <button className="vg-lb-nav vg-lb-next" onClick={onNext}>›</button>

        <video
          key={project.file}
          className="vg-lb-video"
          src={`https://pub-340c09903d0b49fea4aec85224bcb1bb.r2.dev/${project.file}`}
          controls
          autoPlay
          playsInline
        />
        <div className="vg-lb-info">
          <span className="vg-lb-category">{project.category}</span>
          <h2 className="vg-lb-title">{project.title}</h2>
        </div>
      </div>
    </div>
  )
}

// Main gallery component
export function VideoGallery() {
  const [activeCategory, setActiveCategory] = useState('All')
  const [lightboxIndex, setLightboxIndex] = useState<number | null>(null)

  const filtered = activeCategory === 'All'
    ? PROJECT_DATA
    : PROJECT_DATA.filter(p => p.category === activeCategory)

  const openLightbox = useCallback((index: number) => setLightboxIndex(index), [])
  const closeLightbox = useCallback(() => setLightboxIndex(null), [])
  const prevLightbox = useCallback(() => setLightboxIndex(i => i !== null ? (i - 1 + filtered.length) % filtered.length : null), [filtered.length])
  const nextLightbox = useCallback(() => setLightboxIndex(i => i !== null ? (i + 1) % filtered.length : null), [filtered.length])

  return (
    <div className="vg-root">
      {/* Filter tabs */}
      <div className="vg-filters">
        {ALL_CATEGORIES.map(cat => (
          <button
            key={cat}
            className={`vg-filter-btn ${activeCategory === cat ? 'vg-filter-btn--active' : ''}`}
            onClick={() => setActiveCategory(cat)}
          >
            {cat}
          </button>
        ))}
      </div>

      {/* Results count */}
      <p className="vg-count">{filtered.length} Projects</p>

      {/* Grid */}
      <div className="vg-grid">
        {filtered.map((project, i) => (
          <VideoCard
            key={project.file}
            project={project}
            index={i}
            onClick={() => openLightbox(i)}
          />
        ))}
      </div>

      {/* Lightbox */}
      {lightboxIndex !== null && (
        <Lightbox
          project={filtered[lightboxIndex]}
          onClose={closeLightbox}
          onPrev={prevLightbox}
          onNext={nextLightbox}
        />
      )}
    </div>
  )
}
